### PR TITLE
Update License to well-known / policy compliant

### PR DESCRIPTION
**Pull request by felddy**
Please consider updating this project's license to [`CC0-v1`](https://choosealicense.com/licenses/cc0-1.0/).

`CC0-v1` is adopted by [all other projects in the cisagov repository](https://github.com/search?utf8=✓&q=org%3Acisagov+license%3Acc0-1.0&type=Repositories&ref=advsearch&l=&l=), and recommended by the us open-source policy.

For additional information please see:
* https://project-open-data.cio.gov/open-licenses/
* https://choosealicense.com/licenses/cc0-1.0

### CODE REVIEW

**Review by jsf9k — COMMENTED** [review]
This looks good to me, but it's up to the Sogu team to choose an appropriate license.  I won't approve this since I can't choose for them.

I agree wholeheartedly that choosing an existing license is better than rolling your own.

**Review by h-m-f-t — APPROVED** [review]

**Comment by h-m-f-t** [comment]
Welcome @cisagov/sogu team! I "approve" these changes, but won't merge  them. (Also, you should be able to lock down who has merge rights on your project, if that's desired.)

**Comment by michael-tipton** [comment]
Mark I sent you an email to your DHS account. If you could, please review and reply. Thank you.

**Comment by felddy** [comment]
@michael-tipton,  I've got your email and will review.  Thanks for working with Rosemary. (She helped us with the CSET licenses.)

**Comment by felddy** [comment]
@michael-tipton, I read through the email from Rosemary and the attached document `TOU_Exel2Stix Open Source Distribution_04.22.2019.pdf`  

This document seems to be for something called `EXCEL2STIX, VERSION 1.0a`  and not the `SoguFileSearch.psm1` script that is in this repository.    

Did some comm lines get tangled here?  I think we're moving in the right direction.

**Pull request closed without merging**
